### ISSUE TITLE
Bug- consumes file handles at a huge rate

### ISSUE THREAD

**Issue by davidwkerr** [OnionIoT/Omega2-Dash#1]
Consumes file handles at the rate of about 22 per second. 

I have a totally different, independent project which has the same fault. My project consumes them at about 30 per second and seg faults when the open file handles exceeds 65000.

If you remove the call to task handler in the main loop, the problem goes away but of course the demo no longer functions properly. If you increase the delay in the main loop, the creation of file handles slows down.

This problem does not happen in the simulator (at least, not in mine- Eclipse with SDL2).

So something in lvgl or the Omega2 libraries is creating thousands of file handles. Most likely in the task manager area.

Regds,
David

**Comment by davidwkerr** [comment]
I have tried on two different Omega-dash units and also tried updating to:
Device Firmware Version: 0.3.2 b233
Still a problem.
I meant to mention that the example code also segfaults over 65,700 file handles.

**Comment by greenbreakfast** [comment]
Yep, there was a memory leak in the code for the Omega2 Dash touch IC. It's now been fixed and the binaries updated. 
See the terminal output below that shows the file handles holding steady at 322 five minutes after the program was launched.

The code in this repo under `demo/littlev-demo` is meant to be a quick and dirty demo for showing how lvgl works and runs on the Omega2 Dash. 
We don't recommend building on top of it. **If you're looking for a solid foundation for building an LVGL program for the Omega2 Dash, please see the lvgl quickstart template**: https://github.com/OnionIoT/lv_example

And more info on the memory leak fix here: https://github.com/OnionIoT/lv_drivers/pull/1

---

```
root@Omega-47E2:~# date ; cat /proc/sys/fs/file-nr
Wed Jun 10 18:34:57 GMT 2020
317	0	12442
root@Omega-47E2:~# date ; /tmp/o2-dash-lvgl-demo &
Wed Jun 10 18:35:05 GMT 2020
root@Omega-47E2:~# lv_init
The framebuffer device was opened successfully.
320x240, 16bpp
The framebuffer device was mapped to memory successfully.
lv_test_theme_2
starting loop

root@Omega-47E2:~# date ; cat /proc/sys/fs/file-nr
Wed Jun 10 18:35:09 GMT 2020
322	0	12442
root@Omega-47E2:~# date ; cat /proc/sys/fs/file-nr
Wed Jun 10 18:35:37 GMT 2020
322	0	12442
root@Omega-47E2:~# date ; cat /proc/sys/fs/file-nr
Wed Jun 10 18:37:39 GMT 2020
322	0	12442
root@Omega-47E2:~# date ; cat /proc/sys/fs/file-nr
Wed Jun 10 18:40:13 GMT 2020
322	0	12442
```

**Comment by davidwkerr** [comment]
Thanks very much. I had built my program from the driver repository 12 days ago so just missed the fixes.
Best Regds,
Dave
