### ISSUE TITLE
Update for Readme.

### ISSUE THREAD

**Issue by crispyoz** [OnionIoT/Omega2-Dash#2]
Please amend README.md such that all references to the command:

fbi -d /dev/fb0  ........

Should read:

fbi -a -d /dev/fb0 .......

The addition of the "-a" will assist new users who may consider their image as not being displayed when in fact is is just incorrectly scaled.

**Comment by greenbreakfast** [comment]
Good call, thanks!! Feel free to submit a PR in the future!
